from django.urls import path

from user.api.views import (
    RegisterView,
    LoginView,
    LogoutView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    ChangePasswordView,
    VerifyEmailView,
    ProfileCreateView,
    ProfileDetailView,
    ProfileUpdateView,
    ProfileDeleteView,
    OnboardingCreateAPIView,
    OnboardingDetailAPIView,
    OnboardingUpdateAPIView,
    OnboardingDeleteAPIView,
    SymptomListCreateAPIView,
    DietaryStyleListCreateAPIView,
    GoalListCreateAPIView,
    ActivityLevelListCreateAPIView,
    StressLevelListCreateAPIView,
    UserProfileUpdateView,
    VerifyEmailChangeView
)


urlpatterns = [
    # Auth Api
    path(
        'register/',
        RegisterView.as_view(),
        name='register'
    ),
    path(
        'login/',
        LoginView.as_view(),
        name='login'
    ),
    path(
        'logout/',
        LogoutView.as_view(),
        name='logout'
    ),
    path(
        'password-reset/',
        PasswordResetRequestView.as_view(),
        name='password_reset'
    ),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    path(
        'change-password/',
        ChangePasswordView.as_view(),
        name='change_password'
    ),
    path(
        'verify-email/<uidb64>/<token>/',
        VerifyEmailView.as_view(),
        name='verify-email'
    ),
    path(
        'verify-email-change/<uidb64>/<token>/',
        VerifyEmailChangeView.as_view(),
        name='verify_email_change'
    ),
    # Profile Api
    path(
        'profile/create/',
        ProfileCreateView.as_view(),
        name='profile-create'
    ),
    path(
        'profile/me/',
        ProfileDetailView.as_view(),
        name='profile-detail'
    ),
    path(
        'profile/me/update/',
        ProfileUpdateView.as_view(),
        name='profile-update'
    ),
    path(
        'profile/me/delete/',
        ProfileDeleteView.as_view(),
        name='profile-delete'
    ),
    path(
        'profile/update/',
        UserProfileUpdateView.as_view(),
        name='user-profile-update'
    ),

    # Onboarding Api
    path(
        'onboarding/create/',
        OnboardingCreateAPIView.as_view(),
        name='onboarding-create'
    ),
    path(
        'onboarding/<int:pk>/',
        OnboardingDetailAPIView.as_view(),
        name='onboarding-detail'
    ),
    path(
        'onboarding/<int:pk>/update/',
        OnboardingUpdateAPIView.as_view(),
        name='onboarding-update'
    ),
    path(
        'onboarding/<int:pk>/delete/',
        OnboardingDeleteAPIView.as_view(),
        name='onboarding-delete'
    ),
    path(
        'symptoms/',
        SymptomListCreateAPIView.as_view(),
        name='symptom-list-create'
    ),
    path(
        'dietary-styles/',
        DietaryStyleListCreateAPIView.as_view(),
        name='dietary-style-list-create'
    ),
    path(
        'goals/',
        GoalListCreateAPIView.as_view(),
        name='goal-list-create'
    ),
    path(
        'activity-levels/',
        ActivityLevelListCreateAPIView.as_view(),
        name='activity-level-list-create'
    ),
    path(
        'stress-levels/',
        StressLevelListCreateAPIView.as_view(),
        name='stress-level-list-create'
    ),
]
