### Registe

POST http://127.0.0.1:8000/api/v1/register/
Content-Type: application/json

{
  "email": "emon12@gmail.com",
  "password": "Sagor1234#",
  "confirm_password": "Sagor1234#"
}

### Login

POST http://127.0.0.1:8000/api/v1/login/
Content-Type: application/json

{
  "email": "emon12@gmail.com",
  "password": "Sagor1234#"
}

### Logout

POST http://127.0.0.1:8000/api/v1/logout/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzMjA3Nzk3LCJpYXQiOjE3NTMyMDc0OTcsImp0aSI6Ijc4Y2M2ZTY1NWJmYjRhN2Q4YWU5NzlkYjhkM2IzNGUyIiwidXNlcl9pZCI6NX0.RMKpC89LB2unf9Dg0fDUpzj3FqQb9UyaOypPtxh3n0w

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MzI5Mzg5NywiaWF0IjoxNzUzMjA3NDk3LCJqdGkiOiI0OTIxYTJkZTExNWM0NzEwYmU0NDVmMmNhZjgxYWI3YiIsInVzZXJfaWQiOjV9.N6HL3azuOwyHAoUpVifL21Y2yjY8HbwVSoTsCzHT3ec",
}


### Request password reset
POST http://127.0.0.1:8000/api/v1/password-reset/
Content-Type: application/json

{
  "email": "emon12@gmail.com"
}


### Confirm reset (after getting token and uid from console/email)
POST http://127.0.0.1:8000/api/v1/password-reset-confirm/NQ/ctcta4-ed5968a15ae55d209a00259db6050752/
Content-Type: application/json

{
  "password": "NewPassword123",
  "confirm_password": "NewPassword123"
}

