# requests.http
# File to test FENYX FEMME API endpoints using HTTP requests
# Use with VS Code REST Client or similar tools
# Ensure the Django server is running with `python manage.py runserver`
# Replace model IDs (symptoms, dietary_style, etc.) with actual IDs from your database

@baseUrl = http://localhost:8000/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1NzI5MTI4LCJpYXQiOjE3NTU3MjU1MjgsImp0aSI6IjRlZTg5NDFhY2ViMTQ0ODlhMWE2NTdmNDE1YzljYTI1IiwidXNlcl9pZCI6MX0.Co0h-rm-BhsDkM1DngJwekKNxfubxgYvha3WTZV9d2Y

### Login to Obtain JWT Token
POST {{baseUrl}}/login/
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "admin"
}

### POST AI Coach Request
# Replace {{token}} with the 'access' token from the login response
POST {{baseUrl}}/ai/ai-coach/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "user_input": "Hi! can you help me? i feel sick"
}


### GET Dashboard Request
GET {{baseUrl}}/ai/dashboard/
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json


### Get Insight
GET {{baseUrl}}/ai/insight/
Authorization: Bearer {{token}}
Accept: application/json


### Get Goal
GET {{baseUrl}}/ai/goal/
Authorization: Bearer {{token}}
Accept: application/json


### Get Food Suggestions
GET {{baseUrl}}/ai/food/
Authorization: Bearer {{token}}
Accept: application/json


### Get Supplement Suggestions
GET {{baseUrl}}/ai/supplement/
Authorization: Bearer {{token}}
Accept: application/json
